FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY golang/go.mod golang/go.sum ./
RUN go mod download
COPY golang/ .
RUN go build -o main main.go
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
